spring:
  datasource:
    url: jdbc:h2:mem:bookstore_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  h2:
    console:
      enabled: true

springdoc:
  packagesToScan: com.patrickamaro.bookstoremanager
  paths-to-match: /**

logging:
  level:
    br:
      com:
        patrickamaro: DEBUG


info:
  app:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@